// Code generated by counterfeiter. DO NOT EDIT.
package diarizerrunnerfakes

import (
	"sync"

	"github.com/blabbertabber/speechbroker/diarizerrunner"
	"github.com/blabbertabber/speechbroker/ibmservicecreds"
)

type FakeDiarizerRunner struct {
	RunStub        func(flavor, uuid string, creds ibmservicecreds.IBMServiceCreds) error
	runMutex       sync.RWMutex
	runArgsForCall []struct {
		flavor string
		uuid   string
		creds  ibmservicecreds.IBMServiceCreds
	}
	runReturns struct {
		result1 error
	}
	runReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDiarizerRunner) Run(flavor string, uuid string, creds ibmservicecreds.IBMServiceCreds) error {
	fake.runMutex.Lock()
	ret, specificReturn := fake.runReturnsOnCall[len(fake.runArgsForCall)]
	fake.runArgsForCall = append(fake.runArgsForCall, struct {
		flavor string
		uuid   string
		creds  ibmservicecreds.IBMServiceCreds
	}{flavor, uuid, creds})
	fake.recordInvocation("Run", []interface{}{flavor, uuid, creds})
	fake.runMutex.Unlock()
	if fake.RunStub != nil {
		return fake.RunStub(flavor, uuid, creds)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.runReturns.result1
}

func (fake *FakeDiarizerRunner) RunCallCount() int {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return len(fake.runArgsForCall)
}

func (fake *FakeDiarizerRunner) RunArgsForCall(i int) (string, string, ibmservicecreds.IBMServiceCreds) {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return fake.runArgsForCall[i].flavor, fake.runArgsForCall[i].uuid, fake.runArgsForCall[i].creds
}

func (fake *FakeDiarizerRunner) RunReturns(result1 error) {
	fake.RunStub = nil
	fake.runReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeDiarizerRunner) RunReturnsOnCall(i int, result1 error) {
	fake.RunStub = nil
	if fake.runReturnsOnCall == nil {
		fake.runReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.runReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeDiarizerRunner) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeDiarizerRunner) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ diarizerrunner.DiarizerRunner = new(FakeDiarizerRunner)
