// Code generated by counterfeiter. DO NOT EDIT.
package cmdrunnerfakes

import (
	"sync"

	"github.com/blabbertabber/speechbroker/cmdrunner"
)

type FakeCmdRunner struct {
	RunStub        func(cmdArgs ...string)
	runMutex       sync.RWMutex
	runArgsForCall []struct {
		cmdArgs []string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCmdRunner) Run(cmdArgs ...string) {
	fake.runMutex.Lock()
	fake.runArgsForCall = append(fake.runArgsForCall, struct {
		cmdArgs []string
	}{cmdArgs})
	fake.recordInvocation("Run", []interface{}{cmdArgs})
	fake.runMutex.Unlock()
	if fake.RunStub != nil {
		fake.RunStub(cmdArgs...)
	}
}

func (fake *FakeCmdRunner) RunCallCount() int {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return len(fake.runArgsForCall)
}

func (fake *FakeCmdRunner) RunArgsForCall(i int) []string {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return fake.runArgsForCall[i].cmdArgs
}

func (fake *FakeCmdRunner) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCmdRunner) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ cmdrunner.CmdRunner = new(FakeCmdRunner)
