# This is a Dockerfile of CMU Sphinx4
#
# To run:
#   docker run -it blabbertabber/cmu-sphinx4-transcriber bash

FROM blabbertabber/cmu-sphinx4

LABEL authors="Brian Cunnie <brian.cunnie@gmail.com>, Brendan Cunnie <saintbrendan@gmail.com>"
